name: Setup
description: Environment setup

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: package.json
        cache: pnpm
        registry-url: https://registry.npmjs.org

    - shell: bash
      run: |
        pnpm install --frozen-lockfile
        pnpm build
